version: '3'

volumes:
  api_data: {}

services:
  mysql:
    image: mysql:8.0.21
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    healthcheck:
      test: ['CMD', 'mysqladmin' ,'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - api_data:/var/lib/mysql
    ports:
    - 3306:3306
